wp/python/wops/ops/cfm/forms.py
#coding=utf-8

"""
表单类
参考文档：http://wtforms.readthedocs.io/en/latest/
http://wtforms.readthedocs.io/en/latest/genindex.html

字段类型            说明
StringField         文本字段
TextAreaField       多行文本字段
PasswordField       密码文本字段
HiddenField         隐藏文本字段
DateField           文本字段，值为datetime.date格式
DateTimeField       文本字段，值为datetime.datetime格式
IntegerField        文本字段，值为整数
DecimalField        文本字段，值为decimal.Decimal
FloatField          文本字段，值为浮点数
BooleanField        复选框，值为True和False
RadioField          一组单选框
SelectField         下拉列表
SelectMultipleField 下拉列表，可选择多个值
FileField           文件上传字段
SubmitField         表单提交按钮
FormField           把表单作为字段嵌入另一个表单
FieldList           一组指定类型的字段

"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, SelectField, HiddenField, FileField, TextAreaField
from wtforms.validators import DataRequired, ValidationError, Length


class TestForm(FlaskForm):
    """ 定义登录表单 """
    username = StringField(label='UserName', validators=[DataRequired(u"请输入用户名")],
        description=u"请输入用户名",
        render_kw={"required": "required", "class": "form-controal"})
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField(u'登  录')


class ConfigServerForm(FlaskForm):
    """ 定义配置管理表单 """
    form_name = HiddenField('Form Name')
    game_id = SelectField(label=u"游戏版本", coerce=int, id='select_gameid')
    env = SelectField(label=u"SALT分组", id='select_env')
    submit = SubmitField(u'查  询')


class ConfigUploadForm(FlaskForm):
    """ 文件上传 """
    form_name = HiddenField('Form Name')
    custom_name = StringField(label=u'配置文件分发组名',
        validators=[DataRequired()],
        render_kw={"required": 'required',
                   "class": "form-control",
                   "placeholder": u"请输入这组配置文件的名称，用于自我识别"})
    conf_template = FileField(label=u"配置文件模版上传",
        validators=[DataRequired()],
        render_kw={"required": 'required',
                   "class": "form-control"})
    conf_data = TextAreaField(label=u"配置文件动态数据",
        validators=[DataRequired()],
        render_kw={"required": 'required',
                   "class": "form-control",
                   "rows": 10,
                   "placeholder": ur"请输入配置文件动态数据，示例：13799ff4c8113a06,C:\3JianHaoServer01\Data\Config\ServerConfig.xml,10100211,iamIPaddress,10022,202服 万水千山,iamIPaddress,3306,ProjectM;13799ff4c8113a06,C:\3JianHaoServer02\Data\Config\ServerConfig.xml,10100212,iamIPaddress,10023,203服 风流倜傥,iamIPaddress,3306,ProjectM;"})


class ConfigQueryForm(FlaskForm):
    """ 定义配置管理表单 """
    form_name = HiddenField('Form Name')
    game_id = SelectField(label=u"游戏版本", coerce=int, id='select_gameid')
    submit = SubmitField(u'查  询')


class UploadForm(FlaskForm):
    """ 文件上传 """
    conf_template = FileField(label=u"配置文件模版上传", validators=[DataRequired()],
        render_kw={"required": 'required', "class": "form-control"})

wp/python/wops/ops/cmdb/forms.py
#coding=utf-8

"""
表单类
参考文档：http://wtforms.readthedocs.io/en/latest/
http://wtforms.readthedocs.io/en/latest/genindex.html

字段类型            说明
StringField         文本字段
TextAreaField       多行文本字段
PasswordField       密码文本字段
HiddenField         隐藏文本字段
DateField           文本字段，值为datetime.date格式
DateTimeField       文本字段，值为datetime.datetime格式
IntegerField        文本字段，值为整数
DecimalField        文本字段，值为decimal.Decimal
FloatField          文本字段，值为浮点数
BooleanField        复选框，值为True和False
RadioField          一组单选框
SelectField         下拉列表
SelectMultipleField 下拉列表，可选择多个值
FileField           文件上传字段
SubmitField         表单提交按钮
FormField           把表单作为字段嵌入另一个表单
FieldList           一组指定类型的字段

"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, SelectField, HiddenField, FileField, TextAreaField
from wtforms.validators import DataRequired, ValidationError, Length

class ConfigServerForm(FlaskForm):
    """ 定义配置管理表单 """
    form_name = HiddenField('Form Name')
    game_id = SelectField(label=u"游戏版本", coerce=int, id='select_gameid')
    env = SelectField(label=u"SALT分组", id='select_env')
    submit = SubmitField(u'查  询')

wp/python/wops/ops/__init__.py
#coding=utf-8
from datetime import timedelta
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import config



db = SQLAlchemy()

login_manager = LoginManager()
# 设置登录页面的端点
login_manager.login_view = 'auth.login'
# LoginManager 对象的 session_protection 属性可以设为 None 、 'basic' 或 'strong'；设为 'strong' 时,
#+ Flask-Login 会记录客户端 IP地址和浏览器的用户代理信息,如果发现异动就登出用户。
login_manager.session_protection = "strong"
login_manager.login_message = "Please login to access this page."
login_manager.login_message_category = "info"
login_manager.remember_cookie_duration=timedelta(days=1)
login_manager.refresh_view = "login"
login_manager.needs_refresh_message = (
    "To protect your account, please reauthenticate to access this page."
)
login_manager.needs_refresh_message_category = "info"


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    login_manager.init_app(app)

    if app.config['SSL_REDIRECT']:
        from flask_sslify import SSLify
        sslify = SSLify(app)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    from .cfm import cfm as cfm_blueprint
    app.register_blueprint(cfm_blueprint, url_prefix='/cfm')

    from .cmdb import cmdb as cmdb_blueprint
    app.register_blueprint(cmdb_blueprint, url_prefix='/cmdb')


    """
    from .api import api as api_blueprint
    app.register_blueprint(api_blueprint, url_prefix='/api/v1')
    """

    return app

wp/python/wops/ops/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

wp/python/wops/ops/cfm/__init__.py
from flask import Blueprint

cfm = Blueprint('cfm', __name__)

from . import views

wp/python/wops/ops/cfm/views.py
#coding=utf-8
import config
import logging
import os
from . import cfm
from .conf_tools import CreateSLS
from .forms import ConfigServerForm, ConfigUploadForm, ConfigQueryForm, UploadForm
from ..models import TServer, TConfig, TConfigDict, TGametype
from ..libs.common import getID, rename_file
from ops import db
from flask import render_template, flash, request, jsonify, redirect, url_for, session
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from flask_login import login_required, fresh_login_required


logger = logging.getLogger(__name__)

# 文件上传的目录
UPLOAD_PATH = os.path.join(config.basedir, 'static/medias')

engine = create_engine(config.Config.cmdb_oss_engine_url, echo=True)
DB_dict_global = sessionmaker(bind=engine)


def get_gameid():
    ret = []
    for obj_item in TGametype.query.all():
        gameid = obj_item.game_id
        game = obj_item.game
        g_type = obj_item.type

        if game and g_type:
            gametype = game + g_type
        elif game and (not g_type):
            gametype = game
        elif (not game) and g_type:
            gametype = g_type
        else:
            gametype = 'null'
        gametype.encode('utf-8')
        ret.append((gameid, gametype))
    return ret

def get_model_field(model, field):
    try:
        attr = getattr(model, field)
    except AttributeError:
        try:
            attr = getattr(model, field)
        except AttributeError:
            raise AttributeError('Could not find attribute or method '
                                 'named "%s".' % field)
        else:
            return attr(model)
    else:
        if callable(attr):
            attr = attr()
        return attr

def get_salt_group(game_id):
    ret = []
    t_ret = set()  # 集合去重
    for obj_item in TServer.query.filter_by(game_id=game_id).all():
        envs = obj_item.env
        for env in envs.split(','):
            t_ret.add(env)
    for item in t_ret:
        ret.append((item, item))
    return ret

def check_configid(configid):
    if configid is None:
        flash(u"获取配置文件ID错误，请重新选择。")
        return False
    t_num = configid.split(',').__len__()
    if t_num >= 2:
        flash(u"每次只能选择一条数据，请重新选择。")
        return False
    else:
        return True


@cfm.route('/', methods=['GET', 'POST'])
@cfm.route('/server/', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def set_conf_server():
    form = ConfigServerForm(form_name='ConfigServerForm')
    form.game_id.choices = get_gameid()
    game_id = form.game_id.data
    if game_id:
        session['gameid'] = game_id
    else:
        session['gameid'] = None
    # logger.debug(session['gameid'])
    form.env.choices = get_salt_group(game_id)
    env = form.env.data
    if env:
        session['salt_group'] = env
    else:
        session['salt_group'] = None
    # 在这个页面时，清空serverids
    session['serverids'] = None
    return render_template('cfm/conf_servers.html',
                           get_model_field=get_model_field,
                           model_name='.set_conf_server',
                           form=form)


@cfm.route('/api/_api_table_data_tserver/')
@login_required
def _api_table_data_tserver():
    salt_group = session['salt_group']
    gameid = session['gameid']
    logger.debug("GAMEID: {0};;SALT_GROUP: {1}".format(gameid, salt_group))
    if salt_group and gameid:
        page_data = TServer.query.filter(TServer.env.like('%{0}%'.format(salt_group)),
                                         TServer.game_id==gameid).all()
    else:
        page_data = TServer.query.all()
    datas = jsonify([obj_item.to_json() for obj_item in page_data])
    return datas


@cfm.route('/api/_api_table_data_tconfig/')
@login_required
def _api_table_data_tconfig():
    gameid = session['gameid']
    logger.debug("GAMEID: {0}".format(gameid))
    if gameid:
        page_data = TConfig.query.filter_by(game_id=gameid).all()
    else:
        page_data = TConfig.query.all()
    datas = jsonify([obj_item.to_json() for obj_item in page_data])
    return datas



@cfm.route('/manage/', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def set_conf_manage():
    form = ConfigUploadForm(form_name='ConfigUploadForm')
    serverids = session.get('serverids')
    gameid = session.get('gameid')
    if not serverids:
        logger.debug(serverids)
        flash(u"The server_id is null, Please select again.")
        return redirect(url_for('.set_conf_server'))
    if not gameid:
        logger.debug(serverids)
        flash(u"The game_id is null, Please select again.")
        return redirect(url_for('.set_conf_server'))
    if form.validate_on_submit():
        conf_template = form.conf_template.data
        conf_filename = conf_template.filename
        custom_name = form.custom_name.data
        conf_data = form.conf_data.data
        n_id = getID(gameid, serverids, conf_filename)
        logger.debug("{0};{1};{2}".format(gameid, serverids, conf_filename))
        filename_split = conf_filename.split('.')
        re_name = "{0}.{1}".format(n_id, filename_split[-1])
        ret = TConfig.query.filter_by(id=n_id).first()
        if ret:
            o_custom_name = ret.custom_name
            if o_custom_name != custom_name:
                ret.custom_name = custom_name
            o_conf_data = ret.conf_data
            if o_conf_data != conf_data:
                ret.conf_data = conf_data
            db.session.commit()
            flash(u'更新数据成功.')
        else:
            t_data = TConfig(
                id=n_id,
                game_id=session['gameid'],
                servers=session['serverids'],
                custom_name=custom_name,
                conf_name=conf_filename,
                conf_save_name=re_name,
                conf_data=conf_data)
            # 把配置文件相应的数据保存到cmdb_oss库的t_config表
            db.session.add(t_data)
            db.session.commit()
            flash(u'新数据保存成功.')
        # 无论是更新还是保存，都重新上传保存一次文件
        # 文件的全路径
        logger.debug(UPLOAD_PATH)
        if not os.path.exists(UPLOAD_PATH):
            os.makedirs(UPLOAD_PATH)
        filename = os.path.join(UPLOAD_PATH, conf_filename)
        logger.debug(filename)
        conf_template.save(filename)
        rename_file(UPLOAD_PATH, conf_filename, re_name)
        session['configid'] = n_id
    return render_template('cfm/conf_manage.html',
                           model_name='.set_conf_manage',
                           form=form)


@cfm.route('/query/', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def set_conf_query():
    form = ConfigQueryForm(form_name='ConfigQueryForm')
    form.game_id.choices = get_gameid()
    session['gameid'] = form.game_id.data
    return render_template('cfm/conf_query.html',
                           get_model_field=get_model_field,
                           model_name='.set_conf_query',
                           form=form)


@cfm.route('/upload/', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def conf_upload():
    """ 文件上传 """
    if not check_configid(session['configid']):
        return redirect(url_for('.set_conf_query'))
    form = UploadForm()
    if form.validate_on_submit():
        conf_template = form.conf_template.data
        conf_filename = conf_template.filename
        filename_split = conf_filename.split('.')
        re_name = "{0}.{1}".format(session['configid'], filename_split[-1])
        logger.debug(UPLOAD_PATH)
        if not os.path.exists(UPLOAD_PATH):
            os.makedirs(UPLOAD_PATH)
        if conf_template:
            # 文件的全路径
            filename = os.path.join(UPLOAD_PATH, conf_filename)
            logger.debug(filename)
            conf_template.save(filename)
            rename_file(UPLOAD_PATH, conf_filename, re_name)
            flash(u"文件上传成功")
    return render_template("cfm/upload.html",
                           form=form,
                           model_name='.set_conf_query')

@cfm.route('/cat_details/', methods=['GET', 'POST'])
@cfm.route('/cat_details/<int:pk>/', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def conf_cat_details(pk=1):
    """ 查看配置文件内容 """
    if not check_configid(session['configid']):
        return redirect(url_for('.set_conf_query'))
    t_config_dict = TConfigDict.query.filter_by(id=pk).first()
    server_id = t_config_dict.server_id
    conf_path = t_config_dict.conf_path
    conf_id = t_config_dict.conf_id
    try:
        t_server = TServer.query.filter_by(server_id=server_id).first()
        saltid = t_server.saltid
        logger.debug(conf_path)
        logger.debug(saltid)
        new_sls = CreateSLS(conf_id)
        result = new_sls.get_config(saltid, conf_path)
        logger.debug(result)
        return render_template("cfm/conf_cat_details.html",
                               model_name='.conf_cat_table',
                               result=result.decode('utf-8'),
                               conf_path=conf_path)
    except Exception as err:
        logger.error(err)
        flash(u"{0}".format(err))
        return redirect(url_for('.set_conf_query'))


@cfm.route('/cat_table/', methods=['GET', 'POST'])
@login_required
@fresh_login_required
def conf_cat_table():
    """ 查看配置文件内容 """
    if not check_configid(session['configid']):
        return redirect(url_for('.set_conf_query'))
    # 运行之前，先清空表数据，以及恢复ID自增长为1
    # db.dict_global.query(TConfigDict).delete()
    # db.dict_global.commit()
    db_session = DB_dict_global()
    db_session.execute("DELETE FROM t_config_dict;")
    db_session.execute('TRUNCATE TABLE t_config_dict;')
    db_session.commit()
    db_session.close()
    # 把新的数据写入到表
    try:
        t_config = TConfig.query.filter_by(id=session['configid']).first()
        conf_id = t_config.id
        t_dict = CreateSLS.strings_to_dict(t_config.conf_data)
        logger.debug(str(t_dict))
        for server_id in t_dict.keys():
            for item in t_dict.get(server_id):

wp/python/wops/ops/cmdb/__init__.py
from flask import Blueprint

cmdb = Blueprint('cmdb', __name__)

from . import views

wp/python/wops/ops/templates/cfm/conf_query.html
{% extends 'base.html' %}


{% block extracss %}
  <!-- Bootstrap table -->
  <link href="{{ url_for('static', filename='bootstrap-table/dist/bootstrap-table.css', _external=True) }}" rel="stylesheet">
  <!--custom css-->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/table_base.css') }}">
{% endblock %}


{% block title %}
  <title>配置管理</title>
{% endblock %}




{% block breadcrumbs %}
  {{ super() }}
  <li><a href="{{ url_for(model_name) }}">服务器清单</a></li>
{% endblock %}




{% block content %}
  {{ super() }}

  <ul class="nav nav-tabs">
    <li role="presentation" ><a  href="{{ url_for('.set_conf_server') }}">服务器清单</a></li>
    <li role="presentation" ><a  href="{{ url_for('.set_conf_manage') }}">配置管理</a></li>
    <li role="presentation" class="active"><a  href="{{ url_for('.set_conf_query') }}">查询配置</a></li>
  </ul>

  <div class="panel-body" id="bootstrap_table_padding_left" style="padding-bottom:0;">
    <!-- 表单 -->
    <form action="." class="form-inline btn-group" id="toolbar" method="post">
      {% if csrf_token %}{# Support for flask-seasurf #}<input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">{% endif %}
      <!-- 游戏ID -->
      <div class="form-group">
        <div class="form-control system_game_id">{{ form.game_id }}</div>
        {{ form.csrf_token }}
        <button type="submit" id="id_btn_submit" class="form-control btn btn-default" >{{ form.submit.label.text }}</button>
        <a href="{{ url_for('.conf_upload') }}"><button type="button" id="id_btn_reupload_model_config" class="btn btn-default">重新上传配置文件模版</button></a>
        <a href="{{ url_for('.conf_cat_table') }}"><button type="button" id="id_btn_get_config" class="btn btn-default" >查看配置文件</button></a>
        <a href="{{ url_for('.create_sls') }}"><button type="button" id="id_btn_rebulid_config" class="btn btn-default" >重新生成SLS文件</button></a>
        <a href="{{ url_for('.test_push_sls') }}"><button type="button" id="id_btn_test_push_config" class="btn btn-default" >测试推送配置文件</button></a>
        <a href="{{ url_for('.push_sls') }}"><button type="button" id="id_btn_push_config" class="btn btn-default" >推送配置文件</button></a>
      </div>
    </form>
    <!-- //表单 -->
    <table id="table_cfm_tconfig" data-toggle="table" data-url="{{ url_for('cfm._api_table_data_tconfig') }}"
           data-toolbar="#toolbar" data-search="true" data-striped="true" data-show-refresh="true"
           data-show-toggle="true" data-show-columns="true" dataType="json" data-side-pagination="client"
           data-click-to-select="true" data-unique-id="id" data-sort-name="game_id" data-sort-order="desc"
           data-single-select="true">
      <thead>
      <tr>
        <th data-field="state" data-checkbox="true" data-align="center"></th>
        <th data-field="id" data-align="center" data-sortable="true">自编配置ID</th>
        <th data-field="game_id" data-align="center" data-sortable="true">游戏ID</th>
        <th data-field="custom_name" data-align="center" data-sortable="true">自定义配置组名称</th>
        <th data-field="servers" data-align="center" data-sortable="true">SERVERS</th>
        <th data-field="conf_name" data-align="center" data-sortable="true">配置文件名称</th>
        <th data-field="conf_save_name" data-align="center" data-sortable="true">配置文件临时名称</th>
        <th data-field="conf_data" data-halign="center" data-align="left" data-visible="false">配置文件动态数据</th>
      </tr>
      </thead>
    </table>
  </div>


{% endblock %}

{% block extrajs %}
  <script>
    var $table = $('#table_cfm_tconfig');

    function getConfigid() {
      var getselectdata = $table.bootstrapTable('getSelections');
      if (getselectdata.length == 0) {
        alert('请选择需要修改的数据！');
        location.reload();
        return false;
      } else if (getselectdata.length >= 2) {
        alert('请重新选择，不要多选，只能单选！');
        location.reload();
        return false;
      }
      var json_data = eval(getselectdata);
      console.log(json_data);
      console.log(json_data[0].id);
      return json_data[0].id;
    }

    function useConfigid(){
      /*点击按钮之后，获取checkbox选中后的值*/
      $("[id='id_btn_reupload_model_config'], [id='id_btn_get_config'], [id='id_btn_rebulid_config'], [id='id_btn_test_push_config'], [id='id_btn_push_config']").on('click', function(){
        id = getConfigid();
        //发送数据给后台
        $.ajax({
          type: 'POST',
          url: "{{ url_for('._get_id') }}",
          data: JSON.stringify({'id': id}),
          contentType: 'application/json; charset=UTF-8',
          dataType: 'json'
        });
      });
    }
    useConfigid();

  </script>
  <script src="{{ url_for('static', filename='bootstrap-table/dist/bootstrap-table.js', _external=True) }}"></script>
  <!-- put your locale files after bootstrap-table.js -->
  <script src="{{ url_for('static', filename='bootstrap-table/dist/locale/bootstrap-table-zh-CN.js', _external=True) }}"></script>
{% endblock %}

wp/python/wops/ops/templates/cfm/conf_servers.html
{% extends 'base.html' %}


{% block extracss %}
<!-- Bootstrap table -->
<link href="{{ url_for('static', filename='bootstrap-table/dist/bootstrap-table.css', _external=True) }}" rel="stylesheet">
<!--custom css-->
<link rel="stylesheet" href="{{ url_for('static', filename='css/table_base.css') }}">
{% endblock %}

{% block title %}
<title>配置管理</title>
{% endblock %}




{% block breadcrumbs %}
{{ super() }}
<li><a href="{{ url_for(model_name) }}">服务器清单</a></li>
{% endblock %}


{% block content %}
{{ super() }}

<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="{{ url_for('.set_conf_server') }}">服务器清单</a></li>
  <li role="presentation"><a href="{{ url_for('.set_conf_manage') }}">配置管理</a></li>
  <li role="presentation"><a href="{{ url_for('.set_conf_query') }}">查询配置</a></li>
</ul>

<div class="panel-body" id="bootstrap_table_padding_left" style="padding-bottom:0;">
  <!-- 表单 -->
  <form action="." class="form-inline btn-group" id="toolbar" method="post">
    {% if csrf_token %}{# Support for flask-seasurf #}<input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">{% endif %}
    <!-- 游戏ID -->
    <div class="form-group">
      <div class="form-control system_game_id">{{ form.game_id }}</div>
      <div class="form-control system_game_id">{{ form.env }}</div>
      {{ form.csrf_token }}
      <button type="submit" id="id_btn_submit" class="form-control btn btn-default" >{{ form.submit.label.text }}</button>
      <span><textarea id="show_serverids" class="form-control" rows="1" cols="60" placeholder="show server_ids"></textarea></span>
      <button type="button" id="id_btn_getserverid" class="form-control btn btn-default" >提取SERVER_ID</button>
    </div>
  </form>
  <!-- //表单 -->
  <table id="table_cfm_tserver" data-toggle="table" data-url="{{ url_for('cfm._api_table_data_tserver') }}"
         data-toolbar="#toolbar" data-search="true" data-striped="true" data-show-refresh="true"
         data-show-toggle="true" data-show-columns="true" dataType="json" data-side-pagination="client"
         data-click-to-select="true" data-unique-id="server_id" data-sort-name="game_id" data-sort-order="desc">
    <thead>
    <tr>
      <th data-field="state" data-checkbox="true" data-align="center"></th>
      <th data-field="server_id" data-align="center" data-sortable="true">SERVER_ID</th>
      <th data-field="game_id" data-align="center" data-sortable="true">GAME_ID</th>
      <th data-field="ip" data-align="center" data-sortable="true">IP</th>
      <th data-field="netip" data-align="center" data-sortable="true">NETIP</th>
      <th data-field="env" data-align="center" data-sortable="true">SALT分组</th>
      <th data-field="saltid" data-align="center" data-sortable="true">SALT_ID</th>
      <th data-field="hostname" data-align="center" data-sortable="true">HOSTNAME</th>
      <th data-field="os" data-halign="center" data-align="left" data-sortable="true">操作系统</th>
    </tr>
    </thead>
  </table>
</div>
{% endblock %}

{% block extrajs %}
<script>
  $(function(){

    function getServerids(){
      var arrayData = [];
      $('#id_btn_getserverid').click(function () {
        var getselectdata = $('#table_cfm_tserver').bootstrapTable('getSelections');
        if(getselectdata.length == 0)
        {
          alert('请选择需要进行配置管理的服务器！');
          return false;
        }
        var json_data = eval(getselectdata);
        //console.log(json_data[0].server_id);
        for (var i = 0,len = json_data.length; i < len; i++) {
          console.log(json_data[i].server_id);
          var txtvalue = json_data[i].server_id;
          arrayData.push(txtvalue)
        }
        var serverids = arrayData.join(",");
        $("[id='show_serverids']").val(serverids);
        //发送数据给后台
        $.ajax({
          type: 'POST',
          url: "{{ url_for('._get_serverids') }}",
          data: JSON.stringify({'serverids': serverids}),
          contentType: 'application/json; charset=UTF-8',
          dataType: 'json'
        });
        /*清空数组*/
        arrayData = [];
      });
    }
    getServerids();


    /*** 两个下拉菜单联合，下拉1更新后，根据其值更新下拉2的选项 ***/
    // jQuery selection for the 2 select boxes
    var dropdown = {
      game_id: $('#select_gameid'),
      env: $('#select_env')
    };
    // call to update on load
    updateSaltGroup();
    // function to call XHR and update county dropdown
    function updateSaltGroup() {
      var arrayData = [];
      var send = {
        game_id: dropdown.game_id.val()
      };
      dropdown.env.attr('disabled', 'disabled');
      var env_value = dropdown.env.val();
      //console.log(env_value);
      //console.log(dropdown.env.attr('placeholder'));
      dropdown.env.empty();
      $.getJSON("{{ url_for('._get_salt_group') }}", send, function(data) {
        data.forEach(function(item) {
          dropdown.env.append(
              $('<option>', {
                value: item[0],
                text: item[1]
              })
          );
          // alert(item[0]+','+item[1])
          arrayData.push(item[0]);
        });
        dropdown.env.removeAttr('disabled');
        //console.log(arrayData[0]);
        // 清空之后，用选择的值复原，若这个值未在数组中，就用数组中的第一个值
        var result = $.inArray(env_value, arrayData);
        //console.log(result);
        if(result >= 0){
          dropdown.env.val(env_value);
        }else{
          dropdown.env.val(arrayData[0]);
        }
      });
      arrayData = [];
    }
    // event listener to state dropdown change
    dropdown.game_id.on('change', function() {
      updateSaltGroup();
    });

  });
</script>
<script src="{{ url_for('static', filename='bootstrap-table/dist/bootstrap-table.js', _external=True) }}"></script>
<!-- put your locale files after bootstrap-table.js -->
<script src="{{ url_for('static', filename='bootstrap-table/dist/locale/bootstrap-table-zh-CN.js', _external=True) }}"></script>
{% endblock %}